### ISSUE TITLE
The targets can have multiple ?

### ISSUE THREAD

**Issue by penhauer-xiao** [prometheus/client_golang#314]
The targets can have multiple ? like as:
```
  - job_name: redis_exporter

    scrape_interval: 5s

    static_configs:
    - targets: ['192.168.1.2:9121','192.168.1.3:9121' ]

```
